server.port=8090

spring.application.name=bff-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.config.import=optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=*

spring.cloud.openfeign.circuitbreaker.enabled=true

