server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**

        - id: request-service
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/requests/**

        - id: waiting-list-service
          uri: lb://WAITING-LIST-SERVICE
          predicates:
            - Path=/api/waiting-list/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"